# pipeline
---
- name: OCP full 1 workplan 
  hosts: localhost
  gather_facts: false

  vars:

    # General infra

    workplan_name: "ocp_full_1"
    log: "/home/davidfv/experiments/OCP_full/{{ workplan_name }}.log"
    
    embeddings_url: "http://10.10.78.12:8001/v1/embeddings"
    embeddings_key: "none"
    embeddings_model: "nvidia/nv-embedqa-mistral-7b-v2"
    
    llm_url: "http://10.10.78.11:8079/v1"
    llm_key: "none"
    llm_model: "google/gemma-3-27b-it"
    
    bd_host: "192.168.1.68"
    bd_port: "6333"

    # Chunking
   
    chunks: "/home/davidfv/experiments/OCP_full/chunks"
    pdfs: "/home/davidfv/datasets/OCP"
    c_size: 256
    c_overlap: 25 
    
    # Embedding
    embeddings: "/home/davidfv/experiments/OCP_full/embeddings"
    embs_file: "ocp_full_1_embeddings.json"

    # Ingestion
    collection: "ocp_full_1"
    
    # Retrieving
    retriever: "/home/davidfv/experiments/OCP_full/retriever"
    retriever_file: "ocp_full_retrievers.json"
    retriever_top_k: "10"

    # Augmentation
    answers: "/home/davidfv/experiments/OCP_full/answers"
    answers_file: "ocp_full_1_answers.json"
    augmentation_top_k: "10"
    temp: "0.2"
    max_tok: "256"

    # Validation
    validation: "/home/davidfv/experiments/OCP_full/validation"
    validation_file: "ocp_full_1_validation.json"

  tasks:

    #### CHUNKING

    - name: Chunking Modelo 1
      include_role:
        name: local.rag.chunking
      vars:
        pdf_folder: "{{ pdfs }}"
        output_path: "{{ chunks }}"
        chunk_size: "{{ c_size }}"
        chunk_overlap: "{{ c_overlap }}"
     
    #### INDEXING

    - name: Indexing Modelo 1
      include_role:
        name: local.rag.indexer
      vars:
        api_url: "http://10.10.78.12:8001"
        api_key: "{{ embeddings_key }}"
        txt_folder: "{{ chunks }}"
        output_path: "{{ embeddings }}"
        embeddings_file: "{{ embs_file }}"


    #### INGESTION

    - name: Ingestion Modelo 1
      include_role:
        name: local.rag.ingestion
      vars:
        json_path: "{{ embeddings }}/{{ embs_file }}"
        collection_name: "{{ collection }}"
        host_port: "{{ bd_port}}"
        host: "{{ bd_host }}"

    #### RETRIEVER

    - name: Retriever Modelo 1
      include_role:
        name: local.rag.retriever
      vars:
        input_file: "{{ retriever }}/ocp_full_queries.json"
        api_url: "http://10.10.78.12:8001"
        api_key: "{{ embeddings_key }}"
        model_name: "{{ embeddings_model }}"
        host: "{{ bd_host }}"
        port: "{{ bd_port }}"
        collection_name: "{{ collection }}"
        top_k: "{{ retriever_top_k }}"
        output_dir: "{{ retriever }}"
        output_file: "{{ retriever_file }}"

    #### AUGMENTATION
    
    - name: Augmentation Modelo 1
      include_role:
        name: local.rag.augmentation
      vars:
        json_path: "{{ retriever }}/{{ retriever_file }}"
        output_answer: "{{ answers }}/{{ answers_file }}"
        top_k: "{{ augmentation_top_k }}"
        model_name: "{{ llm_model }}"
        api_url: "{{ llm_url }}"
        api_key: "{{ llm_key }}"
        temperature: "{{ temp }}"
        max_tokens: "{{ max_tok }}"

    #### VALIDATION

    
    - name: Validation Modelo 1
      include_role:
        name: local.rag.validation
      vars:
        answer_file: "{{ answers }}/{{ answers_file }}"
        output_validation: "{{ validation }}/{{ validation_file }}"
        embeddings_api_url: "{{ embeddings_url }}"
        embeddings_api_key: "{{ embeddings_key }}"
        embeddings_model_name: "{{ embeddings_model }}"
        llm_api_url: "{{ llm_url }}"
        llm_api_key: "{{ llm_key }}"
        llm_model_name: "{{ llm_model }}"




  