---
# tasks file for augmentation

# Bloque de logging

- name: Arranque de medicion de tiempo
  ansible.builtin.set_fact:
    start_time: "{{ lookup('pipe', 'date +%s') | int }}"

- name: Marca de inicio en log
  ansible.builtin.blockinfile:
    create: true
    path: "{{ log }}"
    marker: ""
    block: |
      AUGMENTATION:
      Comienzo: {{ lookup('pipe', 'date')}}

# Augmentation

- name: Augmentation
  community.docker.docker_container:
    name: "{{ workplan_name }}_augmentation"
    image: "{{ image_name }}"
    state: started
    detach: false
    auto_remove: false
    volumes:
      - "{{ json_path  | dirname }}:/app/{{ json_path | dirname | basename }}/"
      - "{{ output_answer | dirname }}:/app/{{ output_answer | dirname | basename }}/"
    env:

      JSON_PATH: "/app/{{ json_path | dirname | basename }}/{{ json_path  | basename }}"
      OUTPUT_ANSWER: "/app/{{ output_answer | dirname | basename }}/{{ output_answer | basename }}"
      TOP_K: "{{ top_k }}"
      MODEL_NAME: "{{ model_name }}"
      API_URL: "{{ api_url }}"
      API_KEY: "{{ api_key }}"
      TEMPERATURE: "{{ temperature }}"
      MAX_TOKENS: "{{ max_tokens }}"

  register: augmentation_output

  ## Bloque de logging

- name: Parada de medicion de tiempo
  ansible.builtin.set_fact:
    end_time: "{{ lookup('pipe', 'date +%s') | int }}"



- name: Almacena duracion
  ansible.builtin.set_fact:
    total_time: "{{ '%H:%M:%S'  | strftime( end_time | int - start_time | int ) }}"

- name: Marca de inicio en log
  ansible.builtin.blockinfile:
    create: true
    marker: ""
    path: "{{ log }}"
    block: |
      {{ augmentation_output.container.Output }}
      Final: {{ lookup('pipe', 'date') }}
      Duración: {{ total_time }}

- name: Tarea terminada
  debug:
     msg: "Tarea de aumentación finalizada. Log guardado. Duración {{ total_time }} segundos"