# pipeline
---
- name: OCP temp 4 workplan 
  hosts: localhost
  gather_facts: false

  vars:

    # General infra

    base: "/home/davidfv/experiments/top_k/ocp_top_k4"
    workplan_name: "ocp_top_k4"
    log: "{{ base }}/{{ workplan_name }}.log"



    embeddings_url: "http://10.10.78.12:8001/v1/embeddings"
    embeddings_key: "none"
    embeddings_model: "nvidia/nv-embedqa-mistral-7b-v2"
    
    llm_url: "http://10.10.78.11:8079/v1"
    llm_key: "none"
    llm_model: "google/gemma-3-27b-it"
    
    bd_host: "192.168.1.68"
    bd_port: "6333"

    # Chunking
   
    chunks: "{{ base }}/chunks"
    pdfs: "/home/davidfv/datasets/OCP"
    c_size: 400
    c_overlap: 30 
    
    # Embedding
    embeddings: "{{ base }}/embeddings"
    embs_file: "{{ workplan_name }}_embeddings.json"

    # Ingestion
    collection: "{{ workplan_name }}"
    
    # Retrieving
    retriever: "{{ base }}/retriever"
    retriever_file: "{{ workplan_name }}_retrievers.json"
    retriever_top_k: "20"

    # Augmentation
    answers: "{{ base }}/answers"
    answers_file: "{{ workplan_name }}_answers.json"
    augmentation_top_k: "20"
    temp: "1"
    max_tok: "350"

    # Validation
    validation: "{{ base }}/validation"
    validation_file: "{{ workplan_name }}_validation.json"

  tasks:

    #### CHUNKING

    - name: Chunking 
      include_role:
        name: local.rag.chunking
      vars:
        pdf_folder: "{{ pdfs }}"
        output_path: "{{ chunks }}"
        chunk_size: "{{ c_size }}"
        chunk_overlap: "{{ c_overlap }}"
     
    #### INDEXING

    - name: Indexing
      include_role:
        name: local.rag.indexer
      vars:
        api_url: "http://10.10.78.12:8001"
        api_key: "{{ embeddings_key }}"
        txt_folder: "{{ chunks }}"
        output_path: "{{ embeddings }}"
        embeddings_file: "{{ embs_file }}"


    #### INGESTION

    - name: Ingestion
      include_role:
        name: local.rag.ingestion
      vars:
        json_path: "{{ embeddings }}/{{ embs_file }}"
        collection_name: "{{ collection }}"
        host_port: "{{ bd_port}}"
        host: "{{ bd_host }}"

    #### RETRIEVER

    - name: Retriever Modelo 2
      include_role:
        name: local.rag.retriever
      vars:
        input_file: "{{ retriever }}/ocp_full_queries.json"
        api_url: "http://10.10.78.12:8001"
        api_key: "{{ embeddings_key }}"
        model_name: "{{ embeddings_model }}"
        host: "{{ bd_host }}"
        port: "{{ bd_port }}"
        collection_name: "{{ collection }}"
        top_k: "{{ retriever_top_k }}"
        output_dir: "{{ retriever }}"
        output_file: "{{ retriever_file }}"

    #### AUGMENTATION
    
    - name: Augmentation Modelo 2
      include_role:
        name: local.rag.augmentation
      vars:
        json_path: "{{ retriever }}/{{ retriever_file }}"
        output_answer: "{{ answers }}/{{ answers_file }}"
        top_k: "{{ augmentation_top_k }}"
        model_name: "{{ llm_model }}"
        api_url: "{{ llm_url }}"
        api_key: "{{ llm_key }}"
        temperature: "{{ temp }}"
        max_tokens: "{{ max_tok }}"

    #### VALIDATION

    
    - name: Validation Modelo 2
      include_role:
        name: local.rag.validation
      vars:
        answer_file: "{{ answers }}/{{ answers_file }}"
        output_validation: "{{ validation }}/{{ validation_file }}"
        embeddings_api_url: "{{ embeddings_url }}"
        embeddings_api_key: "{{ embeddings_key }}"
        embeddings_model_name: "{{ embeddings_model }}"
        llm_api_url: "{{ llm_url }}"
        llm_api_key: "{{ llm_key }}"
        llm_model_name: "{{ llm_model }}"




  
